
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MrNtlu
 */
public class MainScreen extends javax.swing.JFrame {
    DevamsizlikDB devamsizlikDB=new DevamsizlikDB();
    String situation;
    private Connection con=null;
    private Statement statement=null;
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        showonTable();
        absentcount_field.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        main_table = new javax.swing.JTable();
        lessonname_field = new javax.swing.JTextField();
        absentcount_field = new javax.swing.JTextField();
        absentlimit_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reset_all = new javax.swing.JButton();
        remove_selected = new javax.swing.JButton();
        update_selected = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        plus_button = new javax.swing.JButton();
        decrease_button = new javax.swing.JButton();
        important_note = new javax.swing.JLabel();
        clearFields = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        main_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders Adı", "Devamsızlık Sayısı", "Devamsızlık Limiti", "Durum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        main_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                main_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(main_table);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Ders İsmi:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Devamsızlık Sayısı:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Devamsızlık Limiti:");

        reset_all.setText("Sıfırla");
        reset_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_allActionPerformed(evt);
            }
        });

        remove_selected.setText("Seçileni Sil");
        remove_selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_selectedActionPerformed(evt);
            }
        });

        update_selected.setText("Seçileni Güncelle");
        update_selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_selectedActionPerformed(evt);
            }
        });

        addButton.setText("Ekle");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 51));
        jLabel4.setText("Devamsızlık Hesaplama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        plus_button.setText("+");
        plus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_buttonActionPerformed(evt);
            }
        });

        decrease_button.setText("-");
        decrease_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrease_buttonActionPerformed(evt);
            }
        });

        important_note.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        important_note.setForeground(new java.awt.Color(255, 0, 0));
        important_note.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        clearFields.setText("Temizle");
        clearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsActionPerformed(evt);
            }
        });

        jButton1.setText("Devamsızlık Limiti Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(important_note, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lessonname_field)
                                                .addComponent(absentlimit_field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(decrease_button)
                                            .addGap(18, 18, 18)
                                            .addComponent(absentcount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(plus_button)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reset_all)
                                .addGap(18, 18, 18)
                                .addComponent(remove_selected)
                                .addGap(18, 18, 18)
                                .addComponent(update_selected)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton)
                            .addComponent(jButton1)
                            .addComponent(clearFields))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lessonname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(clearFields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(absentcount_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(plus_button)
                    .addComponent(decrease_button)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(absentlimit_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(important_note, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_all)
                    .addComponent(remove_selected)
                    .addComponent(update_selected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String situation_text(int absent_count,int absent_limit){
        if (absent_count>absent_limit) {
            situation="Devamsızlıktan Kaldı.";
        }
        else if(absent_count==absent_limit){
            situation="Devamsızlık Sınırda.";
        }
        else{
            situation=(absent_limit-absent_count)+" devamsızlık hakkı kaldı.";
        }
        return situation;
    }
    private boolean init;
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try{
            String lesson_name=lessonname_field.getText();
            DefaultTableModel model=(DefaultTableModel)main_table.getModel();
            int absent_count=Integer.parseInt(absentcount_field.getText());
            int absent_limit=Integer.parseInt(absentlimit_field.getText());
            String situation_text=situation_text(absent_count, absent_limit);
            
            for (int i = 0; i < model.getRowCount(); i++) {
                if (lesson_name.equals(model.getValueAt(i, 0))) {
                    init=true;
                    break;
                }
                init=false;
            }
            if (init) {
                JOptionPane.showMessageDialog(this, "Bu ders zaten mevcut");
            }
            else{
                devamsizlikDB.addDatabaseValues(lesson_name, absent_count, absent_limit);
                Object[] addtoTable={lesson_name,absent_count,absent_limit,situation_text};
                model.addRow(addtoTable);
                lessonname_field.setText("");
                absentlimit_field.setText("");
                absentcount_field.setText("0");
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Lütfen Sayı Girin");
            absentcount_field.setText("");
            absentlimit_field.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed
    
    
    public void showonTable(){
        
        DefaultTableModel model=(DefaultTableModel)main_table.getModel();
        String database="Select * From devamsizlik";
        try {
            statement=devamsizlikDB.con.createStatement();
            ResultSet rs=statement.executeQuery(database);
            
            while (rs.next()) {                
                String lesson_name=rs.getString("ders_adi");
                int absent_count=rs.getInt("devamsizlik_sayisi");
                int absent_limit=rs.getInt("devamsizlik_siniri");
                String situation_text=situation_text(absent_count, absent_limit);
                Object[] addtoList={lesson_name,absent_count,absent_limit,situation_text};
                model.addRow(addtoList);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(DevamsizlikDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void reset_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_allActionPerformed
        devamsizlikDB.resetDB();
        DefaultTableModel model=(DefaultTableModel)main_table.getModel();
        model.setRowCount(0);

    }//GEN-LAST:event_reset_allActionPerformed

    private void update_selectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_selectedActionPerformed
        DefaultTableModel model=(DefaultTableModel)main_table.getModel();
        int secili_row=main_table.getSelectedRow();
        if (secili_row==-1) {
            if (main_table.getRowCount()==0){
                important_note.setText("Ders tablosu şuan boş.");
            }
            else{
                important_note.setText("Lütfen güncellenecek bir ders seçin.");
            }
        }
        
        else{
            try {
                statement=devamsizlikDB.con.createStatement();
                String sorgu="UPDATE `devamsizlik` SET `ders_adi` = '"+lessonname_field.getText()+"', `devamsizlik_sayisi` = '"+absentcount_field.getText()
                        +"', `devamsizlik_siniri` = '"+absentlimit_field.getText()+"' WHERE `devamsizlik`.`ders_adi` = '"+lessonname_field.getText()+"'";
                statement.executeUpdate(sorgu);
                
                model.setValueAt(lessonname_field.getText(), secili_row, 0);
                model.setValueAt(absentcount_field.getText(), secili_row, 1);
                model.setValueAt(absentlimit_field.getText(), secili_row, 2);
                int absent_count=Integer.parseInt(absentcount_field.getText());
                int absent_limit=Integer.parseInt(absentlimit_field.getText());
                String situation_text=situation_text(absent_count, absent_limit);
                model.setValueAt(situation_text, secili_row, 3);
                important_note.setText("Ders başarıyla güncellendi.");
                
            } catch (SQLException ex) {
                Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_update_selectedActionPerformed

    private void remove_selectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_selectedActionPerformed
        DefaultTableModel model=(DefaultTableModel)main_table.getModel();
        int choosen_row=main_table.getSelectedRow();
        if (choosen_row==-1) {
            if (main_table.getRowCount()==0) {
                JOptionPane.showMessageDialog(this, "Tablo boş.");
            }
        }
        else{
            String ders_ismi=""+main_table.getValueAt(choosen_row,0);
            model.removeRow(choosen_row);
            devamsizlikDB.deleteDatabaseValue(ders_ismi);
            lessonname_field.setText("");
            absentcount_field.setText("0");
            absentlimit_field.setText("");
        }
    }//GEN-LAST:event_remove_selectedActionPerformed

    private void plus_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_buttonActionPerformed
        int absentcount_plus=Integer.parseInt(absentcount_field.getText());
        absentcount_field.setText(""+(absentcount_plus+1));
    }//GEN-LAST:event_plus_buttonActionPerformed

    private void decrease_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrease_buttonActionPerformed
        int absentcount_plus=Integer.parseInt(absentcount_field.getText());
        if (absentcount_plus<=0) {
            important_note.setText("Sayı sıfırdan düşük olamaz.");
        }
        else{
            important_note.setText("");
            absentcount_field.setText(""+(absentcount_plus-1));
        }
        
    }//GEN-LAST:event_decrease_buttonActionPerformed

    private void main_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_tableMouseClicked
        
        DefaultTableModel model=(DefaultTableModel)main_table.getModel();
        
        int choosen_row=main_table.getSelectedRow();
        lessonname_field.setText(model.getValueAt(choosen_row, 0).toString());
        absentcount_field.setText(model.getValueAt(choosen_row, 1).toString());
        absentlimit_field.setText(model.getValueAt(choosen_row, 2).toString());
        
    }//GEN-LAST:event_main_tableMouseClicked

    private void clearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsActionPerformed
        lessonname_field.setText("");
        absentcount_field.setText("");
        absentlimit_field.setText("");
        important_note.setText("");
    }//GEN-LAST:event_clearFieldsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        absentlimitCalculate alCal=new absentlimitCalculate(this, true);
        alCal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absentcount_field;
    public static javax.swing.JTextField absentlimit_field;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearFields;
    private javax.swing.JButton decrease_button;
    private javax.swing.JLabel important_note;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lessonname_field;
    public javax.swing.JTable main_table;
    private javax.swing.JButton plus_button;
    private javax.swing.JButton remove_selected;
    private javax.swing.JButton reset_all;
    private javax.swing.JButton update_selected;
    // End of variables declaration//GEN-END:variables
}
